# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: appiumandroid

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [25]
        target: [default]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/setup-node@v3.4.1   
      with:
       node-version: 16  
    - run: |  
           npm install -g appium@v1.20.2
           appium -v
           appium &>/dev/null &
    - name: Run Appium Testes     
      uses: reactivecircus/android-emulator-runner@v2
      with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: pixel_4
          script: mvn clean test -Pandroid
       
       
